#
# ./configure --has-doc
#

doc: doc_man

# -*- mode:makefile-gmake -*-
#
# ./configure --has-doc
#
# 1. install groff.
# 2. groff -> troff -> nroff -> runoff.
# 3. how to make a sample man page.
# 4. and convert the man page to texinfo.
# 5. how to make a texinfo file from scratch.
#

# eof
