
math: geo $(bin_path)math$(nm_binext)

math_cflags := $(CFLAGS) $(NM_INCS)
math_ldflags := 


$(tmp_path)math$(nm_objext): $(src_path)math1.c
	$(CC) $(math_cflags) -c $^ $(nm_objout)$@


$(bin_path)math$(nm_binext): $(tmp_path)math$(nm_objext) \
$(lib_path)libgeo.lib
	$(CC) $(CFLAGS) $(math_ldflags) $^ $(nm_binout)$@
