

math_binout := $(bin_path)math$(bin_ext)

math: geo $(math_binout)

math_cflags := $(CFLAGS) $(INC)
math_ldflags := 

$(math_binout): $(src_path)math1.c $(lib_path)libgeo.lib
	$(CC) $(math_cflags) $^ $(bin_out)$@

math_test: math
	PATH=$(lib_path) $(math_binout)
